package com.example.vinilos.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB59F)
val md_theme_dark_onPrimary = Color(0xFF5F1600)
val md_theme_dark_primaryContainer = Color(0xFF802A0E)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_secondary = Color(0xFFFFB2BD)
val md_theme_dark_onSecondary = Color(0xFF670024)
val md_theme_dark_secondaryContainer = Color(0xFF900037)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9DD)
val md_theme_dark_tertiary = Color(0xFFCFCB55)
val md_theme_dark_onTertiary = Color(0xFF333200)
val md_theme_dark_tertiaryContainer = Color(0xFF4B4900)
val md_theme_dark_onTertiaryContainer = Color(0xFFECE76E)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DC)
val md_theme_dark_surface = Color(0xFF201A18)
val md_theme_dark_onSurface = Color(0xFFEDE0DC)
val md_theme_dark_surfaceVariant = Color(0xFF53433F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BC)
val md_theme_dark_outline = Color(0xFFA08C87)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DC)
val md_theme_dark_inversePrimary = Color(0xFF9F4124)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB59F)
val md_theme_dark_outlineVariant = Color(0xFF53433F)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_blue_01 = Color(0xFF006DAA)
val md_theme_dark_blue_02 = Color(0xFF002C44)
val md_theme_dark_blue_03 = Color(0xFF3D63AC)
val md_theme_dark_blue_04 = Color(0xFF192846)
val md_theme_dark_oxford_blue = Color(0xFF061A40)
val md_theme_dark_oxford_orange = Color(0xFFFF9800)

